version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: DockerFile
    container_name: 'elenor_app'
    restart: always
    command: >
      sh -c "
          poetry run python3 manage.py migrate;
          poetry run python3 manage.py runserver 0.0.0.0:8000;
        "
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      -

  postgres:
    restart: always
    image: postgres:16
    container_name: 'elenor_db'
    volumes:
      - ./dbdata:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${NAME_DB}
      - POSTGRES_USER=${USER_DB}
      - POSTGRES_PASSWORD=${PASSWORD_DB}
      - POSTGRES_EXTENSIONS=gin_trgm_ops
    ports:
      - "${POSTGRES_PORT:-5432}:5432"