# The base image we want to inherit from
FROM python:3.12.0-bullseye


# set ENV
ENV PYTHONFAULTHANDLER=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONHASHSEED=random
ENV PATH "./.local/bin:$PATH"
ENV PIP_NO_CACHE_DIR=off
ENV PIP_DISABLE_PIP_VERSION_CHECK=1
ENV PIP_DEFAULT_TIMEOUT=100


# update and install dependency
RUN apt-get update
RUN pip install --upgrade pip
RUN pip install poetry


# set work directory
WORKDIR /app


# Copy packages
COPY pyproject.toml  .
COPY poetry.lock .


# Install Packages
RUN poetry lock
RUN poetry install


# copy project
COPY . .

