# The base image we want to inherit from
FROM python:3.12.0-bullseye

# set ENV
ENV PYTHONFAULTHANDLER=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONHASHSEED=random

ENV PIP_NO_CACHE_DIR=off
ENV PIP_DISABLE_PIP_VERSION_CHECK=on
ENV PIP_DEFAULT_TIMEOUT=100

ENV POETRY_CACHE_DIR='/var/cache/pypoetry'


# System update:
RUN apt-get update
RUN pip install --upgrade pip

# set work directory
WORKDIR /app

COPY pyproject.toml  .
COPY poetry.lock .


RUN poetry install

# copy project
COPY . .