# The base image we want to inherit from
FROM python:3.12.0-bullseye

# set ENV
ENV PYTHONFAULTHANDLER=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONHASHSEED=random

ENV PIP_NO_CACHE_DIR=off
ENV PIP_DISABLE_PIP_VERSION_CHECK=1
ENV PIP_DEFAULT_TIMEOUT=100




RUN pip install poetry


# set work directory
WORKDIR /app

ENV PATH "./.local/bin:$PATH"

COPY pyproject.toml  .
COPY poetry.lock .

RUN poetry lock
RUN poetry install


# copy project
COPY . .

