# Generated by Django 4.2.10 on 2024-06-08 09:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4d480a9a-869a-46e1-a6c2-ef335c3a1d26'), unique=True),
        ),
    ]
